export const applianceItems = [
  { id: "2001", name: "TV", image: "/icons/appliance/Tv.jpeg" },
  { id: "2002", name: "모니터", image: "/icons/appliance/Moniter.jpeg" },
  { id: "2003", name: "PC/데스크탑", image: "/icons/appliance/Pc.jpeg" },
  { id: "2004", name: "세탁기", image: "/icons/appliance/WashingMachine.jpeg" },
  { id: "2005", name: "건조기", image: "/icons/appliance/Dryer.jpeg" },
  { id: "2006", name: "청소기", image: "/icons/appliance/VacuumCleaner.jpeg" },
  { id: "2007", name: "의류관리기", image: "/icons/appliance/ClothingCare.jpeg" },
  { id: "2008", name: "냉장고", image: "/icons/appliance/Refrigerator.jpeg" },
  { id: "2009", name: "전자레인지", image: "/icons/appliance/Microwave.jpeg" },
  { id: "2010", name: "가스레인지", image: "/icons/appliance/GasStove.jpeg" },
  { id: "2011", name: "정수기", image: "/icons/appliance/WaterPurifier.jpeg" },
  { id: "2012", name: "에어컨", image: "/icons/appliance/Aircon.jpeg" },
  { id: "2013", name: "공기청정기", image: "/icons/appliance/AirPurifier.jpeg" },
  { id: "2014", name: "선풍기", image: "/icons/appliance/Fan.jpeg" },
  { id: "2015", name: "안마의자", image: "/icons/appliance/MassageChair.jpeg" },
];
