export const furnitureItems = [
  { id: "1001", name: "침대", image: "/icons/furniture/Bed.jpeg" },
  { id: "1002", name: "쇼파", image: "/icons/furniture/Sofa.jpeg" },
  { id: "1003", name: "옷장-단품", image: "/icons/furniture/WardrobeSing.jpeg" },
  { id: "1004", name: "옷장-연결장", image: "/icons/furniture/WardrobeCombined.jpeg" },
  { id: "1005", name: "행거", image: "/icons/furniture/Hanger.jpeg" },
  { id: "1006", name: "시스템행거", image: "/icons/furniture/SystemHanger.jpeg" },
  { id: "1007", name: "화장대", image: "/icons/furniture/DressingTable.jpeg" },
  { id: "1008", name: "수납장/서랍장", image: "/icons/furniture/Drawer.jpeg" },
  { id: "1009", name: "진열장", image: "/icons/furniture/Display.jpeg" },
  { id: "1010", name: "선반", image: "/icons/furniture/Shelf.jpeg" },
  { id: "1011", name: "거실장/TV장", image: "/icons/furniture/TvCabinet.jpeg" },
  { id: "1012", name: "책장", image: "/icons/furniture/Bookshelf.jpeg" },
  { id: "1013", name: "책상", image: "/icons/furniture/Desk.jpeg" },
  { id: "1014", name: "테이블/식탁", image: "/icons/furniture/DiningTable.jpeg" },
  { id: "1015", name: "의자", image: "/icons/furniture/Chair.jpeg" },
];
